# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
# answer_mode: upside_down | reveal_at_time | shown | hidden
custom_fields:
  answer_mode: upside_down
  reveal_time: "18:00"

# override variables
variables:
  trmnl: {}
